"""Added ordernum fields

Revision ID: 2eb38a0a6fd2
Revises: 43ff41db1d13
Create Date: 2013-05-31 13:48:22.765809

"""

# revision identifiers, used by Alembic.
revision = '2eb38a0a6fd2'
down_revision = '43ff41db1d13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tfoms_standart_tree', sa.Column('ordernum', sa.Integer(), nullable=True))
    op.add_column('tfoms_tags_tree', sa.Column('ordernum', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tfoms_tags_tree', 'ordernum')
    op.drop_column('tfoms_standart_tree', 'ordernum')
    ### end Alembic commands ###
