"""Initial migration

Revision ID: 43ff41db1d13
Revises: None
Create Date: 2013-05-30 18:28:00.482217

"""

# revision identifiers, used by Alembic.
revision = '43ff41db1d13'
down_revision = None

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from application.app import db, app
    from restore import restore
    with app.app_context():
        db.create_all()
        restore()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tfoms_standart_tree')
    op.drop_table('tfoms_tags_tree')
    op.drop_table('tfoms_tag_template_type')
    op.drop_table('tfoms_template')
    op.drop_table('tfoms_template_type')
    op.drop_table('tfoms_tag')
    op.drop_table('tfoms_download_type')
    op.drop_table('tfoms_config_variables')
    ### end Alembic commands ###
